# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-24 15:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gz_order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=20)),
                ('order_type', models.IntegerField(default=0)),
                ('order_statue', models.CharField(max_length=100)),
                ('store_no', models.CharField(max_length=20)),
                ('store_name', models.CharField(blank=True, max_length=20)),
                ('gzj_no', models.IntegerField(default=0)),
                ('gzj_img', models.CharField(blank=True, max_length=200)),
                ('gz_no', models.CharField(max_length=100)),
                ('gz_price', models.IntegerField(blank=True, default=0)),
                ('gz_goods_no', models.CharField(blank=True, max_length=300)),
                ('gz_goods_img', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'verbose_name': '\u8ba2\u5355\u5217\u8868',
                'verbose_name_plural': '\u8ba2\u5355\u5217\u8868',
            },
        ),
        migrations.CreateModel(
            name='gz_order_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=20)),
                ('order_type', models.IntegerField(default=0)),
                ('order_statue', models.CharField(max_length=100)),
                ('store_no', models.CharField(max_length=20)),
                ('store_name', models.CharField(blank=True, max_length=20)),
                ('store_phone', models.CharField(blank=True, max_length=20)),
                ('store_img_url', models.CharField(blank=True, max_length=100)),
                ('store_address', models.CharField(blank=True, max_length=200)),
                ('gzj_no', models.IntegerField(default=0)),
                ('gzj_img', models.CharField(blank=True, max_length=200)),
                ('gzj_price', models.IntegerField(blank=True, default=0)),
                ('gz_no', models.CharField(max_length=100)),
                ('gz_price', models.IntegerField(blank=True, default=0)),
                ('gz_content', models.CharField(blank=True, max_length=200)),
                ('use_no', models.IntegerField(default=0)),
                ('use_phone', models.CharField(max_length=20)),
                ('gz_goods_no', models.CharField(blank=True, max_length=300)),
                ('gz_goods_img', models.CharField(blank=True, max_length=300)),
                ('gz_goods_content', models.CharField(blank=True, max_length=300)),
                ('gz_goods_price', models.CharField(blank=True, max_length=300)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GzOrder.gz_order')),
            ],
            options={
                'verbose_name': '\u8ba2\u5355\u8be6\u60c5',
                'verbose_name_plural': '\u8ba2\u5355\u8be6\u60c5',
            },
        ),
    ]
