# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-25 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gz_cell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='\u683c\u5b50\u67b6\u540d\u79f0')),
                ('width', models.IntegerField(default=0, verbose_name='\u5bbd\u5ea6')),
                ('height', models.IntegerField(default=0, verbose_name='\u9ad8\u5ea6')),
                ('cell_num', models.IntegerField(default=0, verbose_name='\u683c\u5b50\u6570')),
                ('cell_img', models.ImageField(upload_to='img', verbose_name='\u683c\u5b50\u56fe\u7247')),
            ],
            options={
                'verbose_name': '\u683c\u5b50\u67b6',
                'verbose_name_plural': '\u683c\u5b50\u67b6',
            },
        ),
        migrations.CreateModel(
            name='gz_cell_manange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell_name', models.CharField(max_length=20, verbose_name='\u683c\u5b50\u67b6\u540d\u79f0')),
                ('cell_no', models.CharField(max_length=20, verbose_name='\u683c\u5b50\u67b6\u7f16\u53f7')),
                ('store_name', models.CharField(max_length=20, verbose_name='\u5e97\u94fa\u540d\u79f0')),
                ('store_address', models.CharField(max_length=200, verbose_name='\u5e97\u94fa\u5730\u5740')),
                ('store_phone', models.CharField(max_length=20, verbose_name='\u5e97\u94fa\u7535\u8bdd')),
                ('use_cell_width', models.IntegerField(default=0, verbose_name='\u4f7f\u7528\u683c\u5b50\u5bbd\u5ea6')),
                ('use_cell_height', models.IntegerField(default=0, verbose_name='\u4f7f\u7528\u683c\u5b50\u9ad8\u5ea6')),
                ('use_cell_num', models.IntegerField(default=0, verbose_name='\u4f7f\u7528\u683c\u5b50\u4e2a\u6570')),
            ],
            options={
                'verbose_name': '\u683c\u5b50\u67b6\u4f7f\u7528',
                'verbose_name_plural': '\u683c\u5b50\u67b6\u4f7f\u7528',
            },
        ),
        migrations.CreateModel(
            name='gz_manange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell_name', models.CharField(blank=True, max_length=20, verbose_name='\u683c\u5b50\u67b6\u540d\u79f0')),
                ('cell_no', models.CharField(blank=True, max_length=20, verbose_name='\u683c\u5b50\u67b6\u7f16\u53f7')),
                ('store_name', models.CharField(blank=True, max_length=20, verbose_name='\u5e97\u94fa\u540d\u79f0')),
                ('store_address', models.CharField(blank=True, max_length=200, verbose_name='\u5e97\u94fa\u5730\u5740')),
                ('store_phone', models.CharField(max_length=20, verbose_name='\u5e97\u94fa\u7535\u8bdd')),
                ('user_name', models.CharField(blank=True, max_length=20, verbose_name='\u7528\u6237\u540d\u79f0')),
                ('user_phone', models.CharField(blank=True, max_length=20, verbose_name='\u7528\u6237\u7535\u8bdd')),
                ('use_cell_num', models.IntegerField(blank=True, default=0, verbose_name='\u4f7f\u7528\u683c\u5b50\u4e2a\u6570')),
                ('use_cellNo_list', models.CharField(blank=True, max_length=200, verbose_name='\u4f7f\u7528\u683c\u5b50\u4e2a\u6570')),
                ('pay_money', models.IntegerField(blank=True, default=0, verbose_name='\u603b\u91d1\u989d')),
                ('start_time', models.CharField(blank=True, max_length=100, verbose_name='\u5f00\u59cb\u65f6\u95f4')),
                ('end_time', models.CharField(blank=True, max_length=100, verbose_name='\u7ed3\u675f\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u683c\u5b50\u4f7f\u7528',
                'verbose_name_plural': '\u683c\u5b50\u4f7f\u7528',
            },
        ),
    ]
