# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-25 15:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='goods_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_name', models.CharField(max_length=30, verbose_name=b'\xe5\x95\x86\xe5\x93\x81\xe5\x9b\xbe\xe7\x89\x87')),
                ('goods_img_one', models.ImageField(upload_to=b'img', verbose_name=b'\xe5\x95\x86\xe5\x93\x81\xe5\x9b\xbe\xe7\x89\x871')),
                ('goods_img_two', models.ImageField(blank=True, upload_to=b'img', verbose_name=b'\xe5\x95\x86\xe5\x93\x81\xe5\x9b\xbe\xe7\x89\x872')),
                ('goods_img_three', models.ImageField(blank=True, upload_to=b'img', verbose_name=b'\xe5\x95\x86\xe5\x93\x81\xe5\x9b\xbe\xe7\x89\x873')),
                ('store_phone', models.CharField(max_length=20, verbose_name=b'\xe5\x95\x86\xe9\x93\xba\xe7\x94\xb5\xe8\xaf\x9d')),
                ('store_name', models.CharField(max_length=300, verbose_name=b'\xe5\x95\x86\xe9\x93\xba\xe5\x90\x8d\xe7\xa7\xb0')),
                ('store_address', models.CharField(max_length=300, verbose_name=b'\xe5\x95\x86\xe9\x93\xba\xe5\x9c\xb0\xe5\x9d\x80')),
                ('user_img_url', models.ImageField(upload_to=b'img', verbose_name=b'\xe7\x94\xa8\xe6\x88\xb7\xe5\x9b\xbe\xe7\x89\x871')),
                ('user_name', models.CharField(max_length=20, verbose_name=b'\xe7\x94\xa8\xe6\x88\xb7\xe5\x90\x8d\xe7\xa7\xb0')),
                ('use_phone', models.CharField(max_length=20, verbose_name=b'\xe7\x94\xa8\xe6\x88\xb7\xe6\x89\x8b\xe6\x9c\xba\xe5\x8f\xb7')),
                ('user_goods_list', models.CharField(max_length=500, verbose_name=b'\xe7\x94\xa8\xe6\x88\xb7\xe5\x85\xb6\xe4\xbb\x96\xe5\x95\x86\xe5\x93\x81')),
                ('price', models.IntegerField(default=0, verbose_name=b'\xe6\x80\xbb\xe4\xbb\xb7\xe6\xa0\xbc')),
                ('order_no', models.CharField(blank=True, max_length=20, verbose_name=b'\xe8\xae\xa2\xe5\x8d\x95\xe5\x8f\xb7')),
                ('order_type', models.IntegerField(blank=True, default=0, verbose_name=b'\xe8\xae\xa2\xe5\x8d\x95\xe7\xb1\xbb\xe5\x9e\x8b')),
                ('discuss_list', models.CharField(blank=True, max_length=500, verbose_name=b'\xe8\xaf\x84\xe8\xae\xba\xe5\x88\x97\xe8\xa1\xa8')),
                ('goods_content', models.CharField(max_length=300, verbose_name=b'\xe5\x95\x86\xe5\x93\x81\xe8\xaf\xa6\xe6\x83\x85')),
                ('goods_little_content', models.CharField(max_length=200, verbose_name=b'\xe5\x95\x86\xe5\x93\x81\xe5\xb0\x8f\xe6\xa0\x87\xe9\xa2\x98')),
            ],
            options={
                'verbose_name': '\u5546\u54c1\u8be6\u60c5',
                'verbose_name_plural': '\u5546\u54c1\u8be6\u60c5',
            },
        ),
        migrations.CreateModel(
            name='gz_find',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_img', models.ImageField(upload_to=b'img', verbose_name=b'\xe5\x95\x86\xe5\x93\x81\xe5\x9b\xbe\xe7\x89\x87')),
                ('goods_name', models.CharField(max_length=20, verbose_name=b'\xe5\x95\x86\xe5\x93\x81\xe5\x90\x8d\xe7\xa7\xb0')),
                ('user_name', models.CharField(max_length=20, verbose_name=b'\xe7\x94\xa8\xe6\x88\xb7\xe5\x90\x8d')),
                ('gz_no', models.IntegerField(default=0, verbose_name=b'\xe6\xa0\xbc\xe5\xad\x90\xe5\x8f\xb7')),
                ('use_no', models.IntegerField(default=0, verbose_name=b'\xe7\x94\xa8\xe6\x88\xb7\xe5\x8f\xb7')),
                ('phone', models.CharField(max_length=20, verbose_name=b'\xe7\x94\xa8\xe6\x88\xb7\xe6\x89\x8b\xe6\x9c\xba\xe5\x8f\xb7')),
                ('goods_price', models.IntegerField(default=0, verbose_name=b'\xe5\x95\x86\xe5\x93\x81\xe4\xbb\xb7\xe6\xa0\xbc')),
                ('goods_content', models.CharField(max_length=300, verbose_name=b'\xe5\x95\x86\xe5\x93\x81\xe8\xaf\xa6\xe6\x83\x85')),
                ('goods_little_content', models.CharField(max_length=200, verbose_name=b'\xe5\x95\x86\xe5\x93\x81\xe5\xb0\x8f\xe6\xa0\x87\xe9\xa2\x98')),
            ],
            options={
                'verbose_name': '\u5546\u54c1',
                'verbose_name_plural': '\u5546\u54c1',
            },
        ),
        migrations.AddField(
            model_name='goods_detail',
            name='gfind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GzFind.gz_find'),
        ),
    ]
