# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-25 03:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gz_find',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_name', models.CharField(max_length=20)),
                ('user_name', models.CharField(max_length=20)),
                ('gz_no', models.IntegerField(default=0)),
                ('use_no', models.IntegerField(default=0)),
                ('phone', models.CharField(max_length=20)),
                ('goods_price', models.IntegerField(default=0)),
                ('goods_content', models.CharField(max_length=300)),
                ('goods_little_content', models.CharField(max_length=200)),
            ],
        ),
    ]
