# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-25 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gz_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, verbose_name='\u7528\u6237\u540d')),
                ('img', models.ImageField(blank=True, upload_to='img', verbose_name='\u7528\u6237\u5934\u50cf')),
                ('age', models.IntegerField(blank=True, default=0, verbose_name='\u5e74\u9f84')),
                ('phone', models.CharField(max_length=20, verbose_name='\u7535\u8bdd')),
                ('sex', models.CharField(blank=True, max_length=20, verbose_name='\u6027\u522b')),
            ],
            options={
                'verbose_name': '\u7528\u6237',
                'verbose_name_plural': '\u7528\u6237',
            },
        ),
    ]
