# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GzUser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gz_user',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
